openapi: 3.0.3
info:
  title: Todo App 2 API Specification
  description: API documentation for the Todo App 2 bounded context.
servers:
  - url: /api/v1
    description: Development Server
tags:
  - name: TodoApp2
    description: Operations related to the TodoApp2 bounded context.
paths:
  /create-todo:
    post:
      summary: Create Todo
      description: Executes the "Create Todo" command.
      operationId: createTodo
      tags:
        - TodoApp2
      responses:
        '200':
          description: 'OK: The resource was updated successfully.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          $ref: '#/components/responses/BadRequest'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTodoRequest'
  /delete-todo:
    post:
      summary: Delete Todo
      description: Executes the "Delete Todo" command.
      operationId: deleteTodo
      tags:
        - TodoApp2
      responses:
        '200':
          description: 'OK: The resource was updated successfully.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          $ref: '#/components/responses/BadRequest'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeleteTodoRequest'
  /get-all-todos:
    get:
      summary: Get All Todos
      description: Retrieves data based on the "Get All Todos" query. This is a synchronous query operation.
      operationId: getAllTodos
      tags:
        - TodoApp2
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetAllTodosResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
  /get-todo-by-id:
    get:
      summary: Get Todo by ID
      description: Retrieves data based on the "Get Todo by ID" query. This is a synchronous query operation.
      operationId: getTodoByID
      tags:
        - TodoApp2
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTodoByIDResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
  /update-todo:
    post:
      summary: Update Todo
      description: Executes the "Update Todo" command.
      operationId: updateTodo
      tags:
        - TodoApp2
      responses:
        '200':
          description: 'OK: The resource was updated successfully.'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '400':
          $ref: '#/components/responses/BadRequest'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTodoRequest'
components:
  schemas:
    CreateTodoRequest:
      type: object
      properties:
        task:
          type: string
          example: Review domain model
      required:
        - task
    DeleteTodoRequest:
      type: object
      properties:
        id:
          type: string
          example: td-7721
      required:
        - id
    Error:
      type: object
      properties:
        message:
          type: string
          example: An error occurred.
    GetAllTodosResponse:
      type: object
      description: Response schema for the Get All Todos query.
      properties:
        id:
          type: string
          description: The id of the Todo.
          example: td-7721
        task:
          type: string
          description: The task of the Todo.
          example: Review domain model
        createdAt:
          type: string
          description: The createdAt of the Todo.
          example: '2023-11-01 09:00:00'
    GetTodoByIDResponse:
      type: object
      description: Response schema for the Get Todo by ID query.
      properties:
        id:
          type: string
          description: The id of the Todo.
          example: td-7721
        task:
          type: string
          description: The task of the Todo.
          example: Review domain model
    Todo:
      type: object
      description: Represents a Todo in the system.
      properties:
        id:
          type: string
          description: Unique identifier for the Todo (primary key).
          example: td-7721
        task:
          type: string
          description: The task of the Todo.
          example: Review domain model
        createdAt:
          type: string
          description: The createdAt of the Todo.
          example: '2023-11-01 09:00:00'
        updatedAt:
          type: string
          description: The updatedAt of the Todo.
          example: '2023-11-01 09:05:00'
      required:
        - id
        - task
    UpdateTodoRequest:
      type: object
      properties:
        task:
          type: string
          example: Review domain model
      required:
        - task
  parameters:
    TodoId:
      name: id
      in: path
      required: true
      description: The unique identifier for the Todo.
      schema:
        type: string
  responses:
    BadRequest:
      description: 'Bad Request: The server cannot or will not process the request due to something that is perceived to be a client error.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalServerError:
      description: 'Internal Server Error: The server has encountered a situation it doesn''t know how to handle.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: 'Not Found: The server can not find the requested resource.'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
